import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';

import '../providers/language_provider.dart';

class AppLocalization {
  static const String english = 'en';
  static const String sinhala = 'si';
  static const String tamil = 'ta';

  static const Map<String, Map<String, String>> _values = {
    english: {
      'profile': 'Profile',
      'somethingWentWrong': 'Something went wrong',
      'tryAgain': 'Try Again',
      'passenger': 'Passenger',
      'accountManagement': 'Account Management',
      'editProfile': 'Edit Profile',
      'language': 'Language',
      'supportLegal': 'Support & Legal',
      'helpSupport': 'Help & Support',
      'contactUs': 'Contact Us',
      'privacyPolicy': 'Privacy Policy',
      'logoutAccount': 'Logout Account',
      'appVersion': 'App Version',
      'logout': 'Logout',
      'logoutConfirm': 'Are you sure you want to sign out?',
      'staySignedIn': 'Stay Signed In',
      'signOut': 'Sign Out',
      'logoutFailed': 'Logout failed',
      'selectLanguage': 'Select Language',
      'englishLabel': 'English',
      'sinhalaLabel': 'Sinhala',
      'tamilLabel': 'Tamil',
      'processing': 'Processing...',
      'loginTitle': 'Log In',
      'loginSubtitle': 'Log in to continue your seamless journey',
      'mobileNumber': 'Mobile Number',
      'pleaseEnterMobileNumber': 'Please enter your mobile number',
      'pleaseEnterValidMobile': 'Please enter a valid mobile number',
      'loginButton': 'Login',
      'verificationCodeSent': 'Verification code sent! Check your SMS.',
      'tooManyRequests': 'Too Many Requests',
      'error': 'Error',
      'failedToSendCode': 'Failed to send verification code',
      'verifying': 'Verifying...',
      'verifyYourNumber': 'Verify Your Number',
      'enterSixDigitCode': 'Enter the 6-digit code sent to',
      'verifyContinue': 'Verify & Continue',
      'didNotReceiveCode': 'Didn\'t receive the code?',
      'resendCode': 'Resend Code',
      'resendInSeconds': 'Resend in {seconds} seconds',
      'changeMobileNumber': 'Change Mobile Number',
      'invalidSixDigitCode': 'Please enter the complete 6-digit code',
      'invalidVerificationCode': 'Invalid verification code. Please try again.',
      'newCodeSent': 'New code sent! Check your SMS.',
      'failedToSendCodeRetry': 'Failed to send code. Please try again.',
      'completeYourProfile': 'Complete Your Profile',
      'enterNameToStart': 'Please enter your name to get started',
      'firstName': 'First Name',
      'lastName': 'Last Name',
      'enterFirstName': 'Enter your first name',
      'enterLastName': 'Enter your Last Name',
      'pleaseEnterFirstName': 'Please enter your first name',
      'pleaseEnterLastName': 'Please enter your last name',
      'firstNameMinChars': 'First name must be at least 2 characters',
      'lastNameMinChars': 'Last name must be at least 2 characters',
      'continue': 'Continue',
      'addMoreDetailsLater':
          'You can add more details later in your profile settings',
      'saving': 'Saving...',
      'failedToCompleteProfile':
          'Failed to complete profile. Please try again.',
      'retry': 'Retry',
      'from': 'From',
      'to': 'To',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'all': 'All',
      'searching': 'Searching...',
      'tripsFound': '{count} trips found',
      'homeNewNotification': 'New notification received',
      'view': 'VIEW',
      'locationsSwapped': 'Locations swapped',
      'searchingTrips': 'Searching for trips...',
      'pleaseWait': 'Please wait',
      'couldNotFindStops': 'Could not find bus stops for selected locations',
      'searchFailedWithError': 'Search failed: {error}',
      'locationPermissionDenied': 'Location permission denied',
      'locationPermissionDeniedForever':
          'Location permission permanently denied. Please enable in settings.',
      'gettingYourLocation': 'Getting your location...',
      'locationSet': 'Location set: {address}',
      'failedGetCurrentLocation': 'Failed to get current location',
      'upcomingTrips': 'Upcoming Trips',
      'viewAll': 'View All',
      'readyToExplore': 'Ready to explore?',
      'specialOfferTitle': 'Special Offer! 🎫',
      'specialOfferMessage': 'Get 25% off on your next trip to Kandy.',
      'enterPickupLocation': 'Enter pickup location',
      'enterDestination': 'Enter destination',
      'selectLocationOnMap': 'Select Location on Map',
      'loadingAddress': 'Loading address...',
      'offersPage': 'Offers Page',
      'toursPage': 'Tours Page',
      'busTracking': 'Bus Tracking',
      'yourLocation': 'Your Location',
      'locationPermissionRequired': 'Location permission required',
      'enableLocation': 'Enable Location',
      'status': 'Status',
      'trackingActive': 'Tracking Active',
      'readyToTrack': 'Ready to Track',
      'route': 'Route',
      'notAvailable': 'N/A',
      'stopTracking': 'Stop Tracking',
      'startTracking': 'Start Tracking',
      'noActiveBooking': 'No Active Booking',
      'bookBusToStartTracking': 'Book a bus to start tracking',
      'bookABus': 'Book a Bus',
      'notifications': 'Notifications',
      'showingUnreadOnly': 'Showing unread only',
      'recentUpdates': 'Your recent updates',
      'markAllRead': 'Mark all read',
      'refresh': 'Refresh',
      'testNotification': 'Test Notification',
      'allNotificationsMarkedRead': 'All notifications marked as read',
      'deleteNotification': 'Delete Notification',
      'removeNotificationConfirm': 'Remove this notification permanently?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'notificationDeleted': 'Notification deleted',
      'noUnreadNotifications': 'No unread notifications',
      'noNotificationsYet': 'No notifications yet',
      'caughtUp': 'You\'re all caught up!',
      'notifyWhenUpdatesArrive': 'We\'ll notify you when updates arrive',
      'oopsSomethingWrong': 'Oops! Something went wrong',
      'welcome': 'Welcome!',
      'notificationSystemReady':
          'Your notification system is now minimal and modern.',
      'justNow': 'Just now',
      'minutesAgo': '{count}m ago',
      'hoursAgo': '{count}h ago',
      'daysAgo': '{count}d ago',
      'lounges': 'Lounges',
      'discoverPremiumLounges': 'Discover and book premium lounges',
      'filterByProvince': 'Filter by Province',
      'allProvinces': 'All Provinces',
      'failedToLoadLounges': 'Failed to load lounges',
      'noLoungesInState': 'No lounges in {state}',
      'noLoungesAvailable': 'No lounges available',
      'tryDifferentState': 'Try selecting a different state',
      'checkBackLaterLounges': 'Check back later for available lounges',
      'showAllLounges': 'Show All Lounges',
      'loungesInStateCount': '{count} lounge(s) in {state}',
      'showingLoungesCount': 'Showing {count} lounges',
      'startingFrom': 'Starting from',
      'available': 'Available',
      'closed': 'Closed',
      'lounge': 'Lounge',
      'searchFailedTitle': 'Search Failed',
      'noScheduledTrips': 'No Scheduled Trips',
      'routeNotFound': 'Route Not Found',
      'changeSearch': 'Change Search',
      'departsAt': 'Departs {time}',
      'departure': 'Departure',
      'arrival': 'Arrival',
      'charging': 'Charging',
      'entertainment': 'Entertainment',
      'refreshments': 'Refreshments',
      'book': 'Book',
      'selectStops': 'Select Stops',
      'boardingPoint': 'Boarding Point',
      'alightingPoint': 'Alighting Point',
      'continueToSeatSelection': 'Continue to Seat Selection',
    },
    sinhala: {
      'profile': 'පැතිකඩ',
      'somethingWentWrong': 'යම් දෝෂයක් සිදු විය',
      'tryAgain': 'නැවත උත්සාහ කරන්න',
      'passenger': 'මගියා',
      'accountManagement': 'ගිණුම් කළමනාකරණය',
      'editProfile': 'පැතිකඩ සංස්කරණය',
      'language': 'භාෂාව',
      'supportLegal': 'සහාය සහ නීති',
      'helpSupport': 'උදව් සහ සහාය',
      'contactUs': 'අප අමතන්න',
      'privacyPolicy': 'රහස්‍යතා ප්‍රතිපත්තිය',
      'logoutAccount': 'ගිණුමෙන් පිටවන්න',
      'appVersion': 'ඇප් අනුවාදය',
      'logout': 'පිටවීම',
      'logoutConfirm': 'ඔබට ඇත්තටම පිටවීමට අවශ්‍යද?',
      'staySignedIn': 'පුරනය වී සිටින්න',
      'signOut': 'පිටවන්න',
      'logoutFailed': 'පිටවීම අසාර්ථක විය',
      'selectLanguage': 'භාෂාව තෝරන්න',
      'englishLabel': 'ඉංග්‍රීසි',
      'sinhalaLabel': 'සිංහල',
      'tamilLabel': 'தமிழ்',
      'processing': 'සැකසෙමින්...',
      'loginTitle': 'පිවිසෙන්න',
      'loginSubtitle': 'ඔබගේ ගමන පහසුවෙන් ඉදිරියට ගෙන යාමට පිවිසෙන්න',
      'mobileNumber': 'ජංගම දුරකථන අංකය',
      'pleaseEnterMobileNumber': 'කරුණාකර ඔබගේ ජංගම අංකය ඇතුළත් කරන්න',
      'pleaseEnterValidMobile': 'වලංගු ජංගම අංකයක් ඇතුළත් කරන්න',
      'loginButton': 'පිවිසෙන්න',
      'verificationCodeSent':
          'සත්‍යාපන කේතය යවා ඇත! SMS පණිවිඩය පරීක්ෂා කරන්න.',
      'tooManyRequests': 'අධික ඉල්ලීම්',
      'error': 'දෝෂයක්',
      'failedToSendCode': 'සත්‍යාපන කේතය යැවීමට අසමත් විය',
      'verifying': 'තහවුරු කරමින්...',
      'verifyYourNumber': 'ඔබගේ අංකය තහවුරු කරන්න',
      'enterSixDigitCode': 'මෙම අංකයට යවූ ඉලක්කම් 6 ක කේතය ඇතුළත් කරන්න',
      'verifyContinue': 'තහවුරු කර ඉදිරියට යන්න',
      'didNotReceiveCode': 'කේතය නොලැබුණාද?',
      'resendCode': 'කේතය නැවත යවන්න',
      'resendInSeconds': 'තත්පර {seconds} කින් නැවත යවයි',
      'changeMobileNumber': 'ජංගම අංකය වෙනස් කරන්න',
      'invalidSixDigitCode': 'සම්පූර්ණ ඉලක්කම් 6 ක කේතය ඇතුළත් කරන්න',
      'invalidVerificationCode': 'සත්‍යාපන කේතය වැරදියි. නැවත උත්සාහ කරන්න.',
      'newCodeSent': 'නව කේතය යවා ඇත! SMS පරීක්ෂා කරන්න.',
      'failedToSendCodeRetry': 'කේතය යැවීමට අසමත් විය. නැවත උත්සාහ කරන්න.',
      'completeYourProfile': 'ඔබගේ පැතිකඩ සම්පූර්ණ කරන්න',
      'enterNameToStart': 'ආරම්භ කිරීමට ඔබගේ නම ඇතුළත් කරන්න',
      'firstName': 'මුල් නම',
      'lastName': 'අවසන් නම',
      'enterFirstName': 'මුල් නම ඇතුළත් කරන්න',
      'enterLastName': 'අවසන් නම ඇතුළත් කරන්න',
      'pleaseEnterFirstName': 'කරුණාකර මුල් නම ඇතුළත් කරන්න',
      'pleaseEnterLastName': 'කරුණාකර අවසන් නම ඇතුළත් කරන්න',
      'firstNameMinChars': 'මුල් නම අවම වශයෙන් අක්ෂර 2 ක් විය යුතුය',
      'lastNameMinChars': 'අවසන් නම අවම වශයෙන් අක්ෂර 2 ක් විය යුතුය',
      'continue': 'ඉදිරියට යන්න',
      'addMoreDetailsLater':
          'පසුව ඔබගේ පැතිකඩ සැකසුම් තුළ වැඩි විස්තර එක් කළ හැක',
      'saving': 'සුරකිමින්...',
      'failedToCompleteProfile':
          'පැතිකඩ සම්පූර්ණ කිරීමට අසමත් විය. නැවත උත්සාහ කරන්න.',
      'retry': 'නැවත උත්සාහ කරන්න',
      'from': 'සිට',
      'to': 'වෙත',
      'today': 'අද',
      'tomorrow': 'හෙට',
      'all': 'සියල්ල',
      'searching': 'සොයමින්...',
      'tripsFound': 'ගමන් {count}ක් හමු විය',
      'homeNewNotification': 'නව දැනුම්දීමක් ලැබුණි',
      'view': 'බලන්න',
      'locationsSwapped': 'ස්ථාන මාරු කරන ලදී',
      'searchingTrips': 'ගමන් සොයමින්...',
      'pleaseWait': 'කරුණාකර රැඳී සිටින්න',
      'couldNotFindStops': 'තෝරාගත් ස්ථාන සඳහා බස් නැවතුම් සොයාගත නොහැක',
      'searchFailedWithError': 'සෙවීම අසාර්ථක විය: {error}',
      'locationPermissionDenied': 'ස්ථාන අවසරය ප්‍රතික්ෂේප විය',
      'locationPermissionDeniedForever':
          'ස්ථාන අවසරය ස්ථිරව ප්‍රතික්ෂේප විය. කරුණාකර සැකසුම් තුළ සක්‍රීය කරන්න.',
      'gettingYourLocation': 'ඔබගේ ස්ථානය ලබා ගනිමින්...',
      'locationSet': 'ස්ථානය සකසා ඇත: {address}',
      'failedGetCurrentLocation': 'වත්මන් ස්ථානය ලබා ගැනීමට අසමත් විය',
      'upcomingTrips': 'ඉදිරි ගමන්',
      'viewAll': 'සියල්ල බලන්න',
      'readyToExplore': 'සංචාරයට සූදානම්ද?',
      'specialOfferTitle': 'විශේෂ දීමනාවක්! 🎫',
      'specialOfferMessage': 'ඊළඟ කඳුළු ගමනට 25% වට්ටමක් ලබාගන්න.',
      'enterPickupLocation': 'ගමන් ආරම්භ ස්ථානය ඇතුළත් කරන්න',
      'enterDestination': 'ගමනාන්තය ඇතුළත් කරන්න',
      'selectLocationOnMap': 'සිතියමේ ස්ථානය තෝරන්න',
      'loadingAddress': 'ලිපිනය පූරණය කරමින්...',
      'offersPage': 'දීමනා පිටුව',
      'toursPage': 'සංචාර පිටුව',
      'busTracking': 'බස් ලුහුබැඳීම',
      'yourLocation': 'ඔබගේ ස්ථානය',
      'locationPermissionRequired': 'ස්ථාන අවසරය අවශ්‍යයි',
      'enableLocation': 'ස්ථානය සක්‍රීය කරන්න',
      'status': 'තත්වය',
      'trackingActive': 'ලුහුබැඳීම සක්‍රීයයි',
      'readyToTrack': 'ලුහුබැඳීමට සූදානම්',
      'route': 'මාර්ගය',
      'notAvailable': 'නැත',
      'stopTracking': 'ලුහුබැඳීම නවත්වන්න',
      'startTracking': 'ලුහුබැඳීම ආරම්භ කරන්න',
      'noActiveBooking': 'සක්‍රීය වෙන් කිරීමක් නැත',
      'bookBusToStartTracking': 'ලුහුබැඳීම ආරම්භ කිරීමට බස් එකක් වෙන් කරන්න',
      'bookABus': 'බස් එකක් වෙන් කරන්න',
      'notifications': 'දැනුම්දීම්',
      'showingUnreadOnly': 'නොකියවූ දැනුම්දීම් පමණක්',
      'recentUpdates': 'ඔබගේ නවතම යාවත්කාලීන',
      'markAllRead': 'සියල්ල කියවූව ලෙස ලකුණු කරන්න',
      'refresh': 'නැවුම් කරන්න',
      'testNotification': 'පරීක්ෂණ දැනුම්දීම',
      'allNotificationsMarkedRead': 'සියලු දැනුම්දීම් කියවූව ලෙස ලකුණු කරන ලදී',
      'deleteNotification': 'දැනුම්දීම මකන්න',
      'removeNotificationConfirm': 'මෙම දැනුම්දීම ස්ථිරවම ඉවත් කරන්නද?',
      'cancel': 'අවලංගු',
      'delete': 'මකන්න',
      'notificationDeleted': 'දැනුම්දීම මකා දැමුවා',
      'noUnreadNotifications': 'නොකියවූ දැනුම්දීම් නැත',
      'noNotificationsYet': 'දැනුම්දීම් තවම නැත',
      'caughtUp': 'ඔබ සියල්ලටම යාවත්කාලීනයි!',
      'notifyWhenUpdatesArrive': 'යාවත්කාලීන ලැබෙන විට අපි දැනුම් දෙන්නෙමු',
      'oopsSomethingWrong': 'අපොයි! කිසියම් දෝෂයක් සිදු විය',
      'welcome': 'සාදරයෙන් පිළිගනිමු!',
      'notificationSystemReady': 'ඔබගේ දැනුම්දීම් පද්ධතිය දැන් සරල හා නවීනයි.',
      'justNow': 'දැන්ම',
      'minutesAgo': 'මිනිත්තු {count}කට පෙර',
      'hoursAgo': 'පැය {count}කට පෙර',
      'daysAgo': 'දින {count}කට පෙර',
      'lounges': 'ලවුන්ජ්',
      'discoverPremiumLounges': 'උසස් ලවුන්ජ් සොයාගෙන වෙන් කරන්න',
      'filterByProvince': 'පළාත අනුව පෙරහන්න',
      'allProvinces': 'සියලු පළාත්',
      'failedToLoadLounges': 'ලවුන්ජ් පූරණය කිරීමට අසමත් විය',
      'noLoungesInState': '{state} තුළ ලවුන්ජ් නොමැත',
      'noLoungesAvailable': 'ලවුන්ජ් නොමැත',
      'tryDifferentState': 'වෙනත් පළාතක් තෝරා බලන්න',
      'checkBackLaterLounges': 'ලවුන්ජ් සඳහා පසුව නැවත පරීක්ෂා කරන්න',
      'showAllLounges': 'සියලු ලවුන්ජ් පෙන්වන්න',
      'loungesInStateCount': '{state} තුළ ලවුන්ජ් {count}ක්',
      'showingLoungesCount': 'ලවුන්ජ් {count}ක් පෙන්වයි',
      'startingFrom': 'ආරම්භක මිල',
      'available': 'ලබා ගත හැක',
      'closed': 'වසා ඇත',
      'lounge': 'ලවුන්ජ්',
      'searchFailedTitle': 'සෙවීම අසාර්ථකයි',
      'noScheduledTrips': 'සැලසුම්ගත ගමන් නැත',
      'routeNotFound': 'මාර්ගය සොයාගත නොහැක',
      'changeSearch': 'සෙවුම වෙනස් කරන්න',
      'departsAt': '{time}ට පිටත් වේ',
      'departure': 'පිටත්වීම',
      'arrival': 'ළඟා වීම',
      'charging': 'ආරෝපණය',
      'entertainment': 'විනෝදාස්වාදය',
      'refreshments': 'අලුත්පාන',
      'book': 'වෙන් කරන්න',
      'selectStops': 'නැවතුම් තෝරන්න',
      'boardingPoint': 'ඇරඹුම් නැවතුම',
      'alightingPoint': 'බැසීමේ නැවතුම',
      'continueToSeatSelection': 'අසුන් තේරීමට ඉදිරියට යන්න',
    },
    tamil: {
      'profile': 'சுயவிவரம்',
      'somethingWentWrong': 'ஏதோ பிழை ஏற்பட்டது',
      'tryAgain': 'மீண்டும் முயற்சிக்கவும்',
      'passenger': 'பயணி',
      'accountManagement': 'கணக்கு மேலாண்மை',
      'editProfile': 'சுயவிவரத்தை திருத்து',
      'language': 'மொழி',
      'supportLegal': 'ஆதரவும் சட்டமும்',
      'helpSupport': 'உதவி மற்றும் ஆதரவு',
      'contactUs': 'எங்களை தொடர்பு கொள்ளவும்',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
      'logoutAccount': 'கணக்கில் இருந்து வெளியேறு',
      'appVersion': 'அப் பதிப்பு',
      'logout': 'வெளியேறு',
      'logoutConfirm': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'staySignedIn': 'உள்நுழைந்தே இருங்கள்',
      'signOut': 'வெளியேறு',
      'logoutFailed': 'வெளியேறல் தோல்வியடைந்தது',
      'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'englishLabel': 'English',
      'sinhalaLabel': 'සිංහල',
      'tamilLabel': 'தமிழ்',
      'processing': 'செயலாக்கப்படுகிறது...',
      'loginTitle': 'உள்நுழை',
      'loginSubtitle': 'உங்கள் பயணத்தை தொடர உள்நுழைக',
      'mobileNumber': 'கைபேசி எண்',
      'pleaseEnterMobileNumber': 'உங்கள் கைபேசி எண்ணை உள்ளிடவும்',
      'pleaseEnterValidMobile': 'சரியான கைபேசி எண்ணை உள்ளிடவும்',
      'loginButton': 'உள்நுழை',
      'verificationCodeSent':
          'சரிபார்ப்பு குறியீடு அனுப்பப்பட்டது! SMS ஐ பார்க்கவும்.',
      'tooManyRequests': 'அதிக கோரிக்கைகள்',
      'error': 'பிழை',
      'failedToSendCode': 'சரிபார்ப்பு குறியீட்டை அனுப்ப முடியவில்லை',
      'verifying': 'சரிபார்க்கப்படுகிறது...',
      'verifyYourNumber': 'உங்கள் எண்ணை சரிபார்க்கவும்',
      'enterSixDigitCode':
          'இந்த எண்ணிற்கு அனுப்பப்பட்ட 6 இலக்க குறியீட்டை உள்ளிடவும்',
      'verifyContinue': 'சரிபார்த்து தொடரவும்',
      'didNotReceiveCode': 'குறியீடு கிடைக்கவில்லையா?',
      'resendCode': 'குறியீட்டை மீண்டும் அனுப்பு',
      'resendInSeconds': '{seconds} விநாடிகளில் மீண்டும் அனுப்பலாம்',
      'changeMobileNumber': 'கைபேசி எண்ணை மாற்று',
      'invalidSixDigitCode': 'முழு 6 இலக்க குறியீட்டை உள்ளிடவும்',
      'invalidVerificationCode':
          'தவறான சரிபார்ப்பு குறியீடு. மீண்டும் முயற்சிக்கவும்.',
      'newCodeSent': 'புதிய குறியீடு அனுப்பப்பட்டது! SMS ஐ பார்க்கவும்.',
      'failedToSendCodeRetry':
          'குறியீட்டை அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'completeYourProfile': 'உங்கள் சுயவிவரத்தை பூர்த்தி செய்யவும்',
      'enterNameToStart': 'தொடங்க உங்கள் பெயரை உள்ளிடவும்',
      'firstName': 'முதல் பெயர்',
      'lastName': 'கடைசி பெயர்',
      'enterFirstName': 'உங்கள் முதல் பெயரை உள்ளிடவும்',
      'enterLastName': 'உங்கள் கடைசி பெயரை உள்ளிடவும்',
      'pleaseEnterFirstName': 'முதல் பெயரை உள்ளிடவும்',
      'pleaseEnterLastName': 'கடைசி பெயரை உள்ளிடவும்',
      'firstNameMinChars': 'முதல் பெயர் குறைந்தது 2 எழுத்துகள் இருக்க வேண்டும்',
      'lastNameMinChars': 'கடைசி பெயர் குறைந்தது 2 எழுத்துகள் இருக்க வேண்டும்',
      'continue': 'தொடரவும்',
      'addMoreDetailsLater':
          'பிறகு சுயவிவர அமைப்புகளில் கூடுதல் விவரங்களை சேர்க்கலாம்',
      'saving': 'சேமிக்கப்படுகிறது...',
      'failedToCompleteProfile':
          'சுயவிவரத்தை பூர்த்தி செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      'from': 'இருந்து',
      'to': 'செல்லும் இடம்',
      'today': 'இன்று',
      'tomorrow': 'நாளை',
      'all': 'அனைத்து',
      'searching': 'தேடுகிறது...',
      'tripsFound': '{count} பயணங்கள் கிடைத்தன',
      'homeNewNotification': 'புதிய அறிவிப்பு வந்துள்ளது',
      'view': 'பார்க்க',
      'locationsSwapped': 'இடங்கள் மாற்றப்பட்டன',
      'searchingTrips': 'பயணங்கள் தேடப்படுகிறது...',
      'pleaseWait': 'தயவு செய்து காத்திருக்கவும்',
      'couldNotFindStops':
          'தேர்ந்தெடுத்த இடங்களுக்கு பேருந்து நிறுத்தங்கள் கிடைக்கவில்லை',
      'searchFailedWithError': 'தேடல் தோல்வி: {error}',
      'locationPermissionDenied': 'இருப்பிட அனுமதி மறுக்கப்பட்டது',
      'locationPermissionDeniedForever':
          'இருப்பிட அனுமதி நிரந்தரமாக மறுக்கப்பட்டுள்ளது. அமைப்புகளில் இயலுமைப்படுத்தவும்.',
      'gettingYourLocation': 'உங்கள் இருப்பிடத்தை பெறுகிறது...',
      'locationSet': 'இருப்பிடம் அமைக்கப்பட்டது: {address}',
      'failedGetCurrentLocation': 'தற்போதைய இருப்பிடத்தை பெற முடியவில்லை',
      'upcomingTrips': 'வரவிருக்கும் பயணங்கள்',
      'viewAll': 'அனைத்தையும் பார்க்க',
      'readyToExplore': 'ஆராய தயாரா?',
      'specialOfferTitle': 'சிறப்பு சலுகை! 🎫',
      'specialOfferMessage':
          'உங்கள் அடுத்த கண்டி பயணத்திற்கு 25% தள்ளுபடி பெறுங்கள்.',
      'enterPickupLocation': 'புறப்படும் இடத்தை உள்ளிடவும்',
      'enterDestination': 'இலக்கை உள்ளிடவும்',
      'selectLocationOnMap': 'வரைபடத்தில் இடத்தைத் தேர்ந்தெடுக்கவும்',
      'loadingAddress': 'முகவரி ஏற்றப்படுகிறது...',
      'offersPage': 'சலுகைகள் பக்கம்',
      'toursPage': 'சுற்றுலா பக்கம்',
      'busTracking': 'பேருந்து கண்காணிப்பு',
      'yourLocation': 'உங்கள் இருப்பிடம்',
      'locationPermissionRequired': 'இருப்பிட அனுமதி தேவை',
      'enableLocation': 'இருப்பிடத்தை இயலுமைப்படுத்தவும்',
      'status': 'நிலை',
      'trackingActive': 'கண்காணிப்பு செயலில் உள்ளது',
      'readyToTrack': 'கண்காணிக்க தயாராக உள்ளது',
      'route': 'பாதை',
      'notAvailable': 'பொருந்தாது',
      'stopTracking': 'கண்காணிப்பை நிறுத்து',
      'startTracking': 'கண்காணிப்பை தொடங்கு',
      'noActiveBooking': 'செயலில் முன்பதிவு இல்லை',
      'bookBusToStartTracking': 'கண்காணிக்க பேருந்தை முன்பதிவு செய்யவும்',
      'bookABus': 'பேருந்தை முன்பதிவு செய்யவும்',
      'notifications': 'அறிவிப்புகள்',
      'showingUnreadOnly': 'படிக்காதவற்றை மட்டும் காட்டுகிறது',
      'recentUpdates': 'உங்கள் சமீபத்திய புதுப்பிப்புகள்',
      'markAllRead': 'அனைத்தையும் படித்ததாக குறிக்கவும்',
      'refresh': 'புதுப்பி',
      'testNotification': 'சோதனை அறிவிப்பு',
      'allNotificationsMarkedRead':
          'அனைத்து அறிவிப்புகளும் படித்ததாக குறிக்கப்பட்டது',
      'deleteNotification': 'அறிவிப்பை நீக்கு',
      'removeNotificationConfirm': 'இந்த அறிவிப்பை நிரந்தரமாக நீக்கவா?',
      'cancel': 'ரத்து செய்',
      'delete': 'நீக்கு',
      'notificationDeleted': 'அறிவிப்பு நீக்கப்பட்டது',
      'noUnreadNotifications': 'படிக்காத அறிவிப்புகள் இல்லை',
      'noNotificationsYet': 'இன்னும் அறிவிப்புகள் இல்லை',
      'caughtUp': 'நீங்கள் அனைத்தையும் பார்த்துவிட்டீர்கள்!',
      'notifyWhenUpdatesArrive': 'புதுப்பிப்புகள் வந்தவுடன் அறிவிப்போம்',
      'oopsSomethingWrong': 'அப்பா! ஏதோ தவறு நடந்துவிட்டது',
      'welcome': 'வரவேற்பு!',
      'notificationSystemReady':
          'உங்கள் அறிவிப்பு அமைப்பு இப்போது எளிமையாகவும் நவீனமாகவும் உள்ளது.',
      'justNow': 'இப்போதுதான்',
      'minutesAgo': '{count}நி முன்',
      'hoursAgo': '{count}மணி முன்',
      'daysAgo': '{count}நாள் முன்',
      'lounges': 'லவுஞ்சுகள்',
      'discoverPremiumLounges':
          'பிரீமியம் லவுஞ்சுகளை கண்டுபிடித்து முன்பதிவு செய்யுங்கள்',
      'filterByProvince': 'மாவட்டம்/மாநிலம் மூலம் வடிகட்டு',
      'allProvinces': 'அனைத்து மாகாணங்கள்',
      'failedToLoadLounges': 'லவுஞ்சுகளை ஏற்ற முடியவில்லை',
      'noLoungesInState': '{state} இல் லவுஞ்சுகள் இல்லை',
      'noLoungesAvailable': 'லவுஞ்சுகள் இல்லை',
      'tryDifferentState': 'வேறு மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
      'checkBackLaterLounges': 'பின்னர் மீண்டும் சரிபார்க்கவும்',
      'showAllLounges': 'அனைத்து லவுஞ்சுகளையும் காட்டு',
      'loungesInStateCount': '{state} இல் {count} லவுஞ்சுகள்',
      'showingLoungesCount': '{count} லவுஞ்சுகள் காட்டப்படுகிறது',
      'startingFrom': 'தொடக்க விலை',
      'available': 'கிடைக்கிறது',
      'closed': 'மூடப்பட்டது',
      'lounge': 'லவுஞ்ச்',
      'searchFailedTitle': 'தேடல் தோல்வி',
      'noScheduledTrips': 'திட்டமிட்ட பயணங்கள் இல்லை',
      'routeNotFound': 'பாதை கிடைக்கவில்லை',
      'changeSearch': 'தேடலை மாற்று',
      'departsAt': '{time} புறப்படும்',
      'departure': 'புறப்படும் இடம்',
      'arrival': 'சேரும் இடம்',
      'charging': 'சார்ஜிங்',
      'entertainment': 'பொழுதுபோக்கு',
      'refreshments': 'இளநீர்/பானம்',
      'book': 'முன்பதிவு செய்',
      'selectStops': 'நிறுத்தங்களைத் தேர்ந்தெடுக்கவும்',
      'boardingPoint': 'ஏறும் இடம்',
      'alightingPoint': 'இறங்கும் இடம்',
      'continueToSeatSelection': 'இருக்கைத் தேர்வுக்கு தொடரவும்',
    },
  };

  static String tr(BuildContext context, String key) {
    final languageCode = context.read<LanguageProvider>().languageCode;
    return _values[languageCode]?[key] ?? _values[english]?[key] ?? key;
  }

  static String languageName(BuildContext context, String languageCode) {
    switch (languageCode) {
      case english:
        return tr(context, 'englishLabel');
      case sinhala:
        return tr(context, 'sinhalaLabel');
      case tamil:
        return tr(context, 'tamilLabel');
      default:
        return tr(context, 'englishLabel');
    }
  }

  static String trWithArgs(
    BuildContext context,
    String key,
    Map<String, String> args,
  ) {
    var value = tr(context, key);
    args.forEach((argKey, argValue) {
      value = value.replaceAll('{$argKey}', argValue);
    });
    return value;
  }
}
