import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';

import '../providers/language_provider.dart';

class AppLocalization {
  static const String english = 'en';
  static const String sinhala = 'si';
  static const String tamil = 'ta';

  static const Map<String, Map<String, String>> _values = {
    english: {
      'profile': 'Profile',
      'somethingWentWrong': 'Something went wrong',
      'tryAgain': 'Try Again',
      'passenger': 'Passenger',
      'greetingWithName': 'Hello {name}!',
      'accountManagement': 'Account Management',
      'editProfile': 'Edit Profile',
      'language': 'Language',
      'supportLegal': 'Support & Legal',
      'helpSupport': 'Help & Support',
      'contactUs': 'Contact Us',
      'privacyPolicy': 'Privacy Policy',
      'getInTouch': 'Get in Touch',
      'contactUsIntro':
          'We\'d love to hear from you! Please fill out the form below or contact us directly.',
      'phoneLabel': 'Phone',
      'emailLabel': 'Email',
      'sendUsAMessage': 'Send us a message',
      'yourName': 'Your Name',
      'yourEmail': 'Your Email',
      'message': 'Message',
      'submitMessage': 'Submit Message',
      'messageSentSuccess': 'Your message has been sent!',
      'yourPrivacyMatters': 'Your Privacy Matters',
      'privacyPolicyIntro':
          'This Privacy Policy describes how your personal information is collected, used, and shared when you use our Passenger Application.',
      'privacySection1Title': '1. Information Collection',
      'privacySection1Body':
          'We collect information that you provide directly to us, such as when you create or modify your account, request services, contact customer support, or otherwise communicate with us. This information may include: name, email, phone number, postal address, profile picture, payment method, and other information you choose to provide.',
      'privacySection2Title': '2. How We Use Information',
      'privacySection2Body':
          'We use the information we collect to provide, maintain, and improve our services, such as to facilitate payments, send receipts, provide products and services you request, and develop new features.',
      'privacySection3Title': '3. Information Sharing',
      'privacySection3Body':
          'We may share the information we collect about you as described in this statement or at the time of collection or sharing, including with third-party service providers who provide services on our behalf.',
      'privacySection4Title': '4. Data Security',
      'privacySection4Body':
          'We take reasonable measures to help protect information about you from loss, theft, misuse and unauthorized access, disclosure, alteration and destruction.',
      'privacyLastUpdated': 'Last updated: February, 2026',
      'logoutAccount': 'Logout Account',
      'appVersion': 'App Version',
      'logout': 'Logout',
      'logoutConfirm': 'Are you sure you want to sign out?',
      'staySignedIn': 'Stay Signed In',
      'signOut': 'Sign Out',
      'logoutFailed': 'Logout failed',
      'selectLanguage': 'Select Language',
      'englishLabel': 'English',
      'sinhalaLabel': 'Sinhala',
      'tamilLabel': 'Tamil',
      'processing': 'Processing...',
      'loginTitle': 'Log In',
      'loginSubtitle': 'Log in to continue your seamless journey',
      'mobileNumber': 'Mobile Number',
      'pleaseEnterMobileNumber': 'Please enter your mobile number',
      'pleaseEnterValidMobile': 'Please enter a valid mobile number',
      'loginButton': 'Login',
      'verificationCodeSent': 'Verification code sent! Check your SMS.',
      'tooManyRequests': 'Too Many Requests',
      'error': 'Error',
      'failedToSendCode': 'Failed to send verification code',
      'verifying': 'Verifying...',
      'verifyYourNumber': 'Verify Your Number',
      'enterSixDigitCode': 'Enter the 6-digit code sent to',
      'verifyContinue': 'Verify & Continue',
      'didNotReceiveCode': 'Didn\'t receive the code?',
      'resendCode': 'Resend Code',
      'resendInSeconds': 'Resend in {seconds} seconds',
      'changeMobileNumber': 'Change Mobile Number',
      'invalidSixDigitCode': 'Please enter the complete 6-digit code',
      'invalidVerificationCode': 'Invalid verification code. Please try again.',
      'newCodeSent': 'New code sent! Check your SMS.',
      'failedToSendCodeRetry': 'Failed to send code. Please try again.',
      'completeYourProfile': 'Complete Your Profile',
      'enterNameToStart': 'Please enter your name to get started',
      'firstName': 'First Name',
      'lastName': 'Last Name',
      'enterFirstName': 'Enter your first name',
      'enterLastName': 'Enter your Last Name',
      'pleaseEnterFirstName': 'Please enter your first name',
      'pleaseEnterLastName': 'Please enter your last name',
      'firstNameMinChars': 'First name must be at least 2 characters',
      'lastNameMinChars': 'Last name must be at least 2 characters',
      'continue': 'Continue',
      'addMoreDetailsLater':
          'You can add more details later in your profile settings',
      'saving': 'Saving...',
      'failedToCompleteProfile':
          'Failed to complete profile. Please try again.',
      'newNotificationReceived': 'New notification received',
      'view': 'VIEW',
      'locationsSwapped': 'Locations swapped',
      'searchingTrips': 'Searching for trips...',
      'pleaseWait': 'Please wait',
      'couldNotFindBusStops': 'Could not find bus stops for selected locations',
      'searchFailed': 'Search failed: {error}',
      'locationPermissionDenied': 'Location permission denied',
      'locationPermissionPermanentlyDenied':
          'Location permission permanently denied. Please enable in settings.',
      'gettingYourLocation': 'Getting your location...',
      'locationSet': 'Location set: {address}',
      'failedToGetCurrentLocation': 'Failed to get current location',
      'upcomingTrips': 'Upcoming Trips',
      'viewAll': 'View All',
      'fromLabel': 'From',
      'toLabel': 'To',
      'enterPickupLocation': 'Enter pickup location',
      'enterDestination': 'Enter destination',
      'recentSearches': 'Recent Searches',
      'searchResults': 'Search Results',
      'useCurrentLocation': 'Use Current Location',
      'detectMyLocationGps': 'Detect my location using GPS',
      'setLocationOnMap': 'Set location on map',
      'tapToSwapLocations': 'Tap to swap locations',
      'busTracking': 'Bus Tracking',
      'locationPermissionRequired': 'Location permission required',
      'enableLocation': 'Enable Location',
      'status': 'Status',
      'trackingActive': 'Tracking Active',
      'readyToTrack': 'Ready to Track',
      'route': 'Route',
      'stopTracking': 'Stop Tracking',
      'startTracking': 'Start Tracking',
      'noActiveBooking': 'No Active Booking',
      'bookBusToStartTracking': 'Book a bus to start tracking',
      'bookABus': 'Book a Bus',
      'yourLocation': 'Your Location',
      'na': 'N/A',
      'notifications': 'Notifications',
      'showingUnreadOnly': 'Showing unread only',
      'yourRecentUpdates': 'Your recent updates',
      'allNotificationsMarkedAsRead': 'All notifications marked as read',
      'deleteNotification': 'Delete Notification',
      'removeNotificationPermanently': 'Remove this notification permanently?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'notificationDeleted': 'Notification deleted',
      'markAllRead': 'Mark all read',
      'refresh': 'Refresh',
      'testNotification': 'Test Notification',
      'welcome': 'Welcome!',
      'notificationSystemReady':
          'Your notification system is now minimal and modern.',
      'noUnreadNotifications': 'No unread notifications',
      'noNotificationsYet': 'No notifications yet',
      'youAreAllCaughtUp': 'You\'re all caught up!',
      'updatesWhenArrive': 'We\'ll notify you when updates arrive',
      'oopsSomethingWentWrong': 'Oops! Something went wrong',
      'justNow': 'Just now',
      'minutesAgo': '{count}m ago',
      'hoursAgo': '{count}h ago',
      'daysAgo': '{count}d ago',
      'lounges': 'Lounges',
      'discoverBookPremiumLounges': 'Discover and book premium lounges',
      'filterByProvince': 'Filter by Province',
      'allProvinces': 'All Provinces',
      'failedToLoadLounges': 'Failed to load lounges',
      'retry': 'Retry',
      'noLoungesInState': 'No lounges in {state}',
      'noLoungesAvailable': 'No lounges available',
      'tryDifferentState': 'Try selecting a different state',
      'checkBackLaterLounges': 'Check back later for available lounges',
      'showAllLounges': 'Show All Lounges',
      'loungesInStateCount': '{count} lounge(s) in {state}',
      'showingLoungesCount': 'Showing {count} lounges',
      'startingFrom': 'Starting from',
      'available': 'Available',
      'closed': 'Closed',
      'noDateSelected': 'No Date Selected',
      'searchFailedTitle': 'Search Failed',
      'noBusesForRouteDate':
          'No buses available for this route on the selected date.',
      'noScheduledTrips': 'No Scheduled Trips',
      'routeNotFound': 'Route Not Found',
      'fromPrefix': 'From: {value}',
      'toPrefix': 'To: {value}',
      'changeSearch': 'Change Search',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'nextMonth': 'Next Month',
      'inDays': 'In {days} days',
      'popularRoutes': 'Popular Routes',
      'daySun': 'Sun',
      'dayMon': 'Mon',
      'dayTue': 'Tue',
      'dayWed': 'Wed',
      'dayThu': 'Thu',
      'dayFri': 'Fri',
      'daySat': 'Sat',
      'monthJan': 'Jan',
      'monthFeb': 'Feb',
      'monthMar': 'Mar',
      'monthApr': 'Apr',
      'monthMay': 'May',
      'monthJun': 'Jun',
      'monthJul': 'Jul',
      'monthAug': 'Aug',
      'monthSep': 'Sep',
      'monthOct': 'Oct',
      'monthNov': 'Nov',
      'monthDec': 'Dec',
      'readyToExplore': 'Ready to explore?',
      'dummyAdTitle1': 'Special Discount 20% Off',
      'dummyAdDesc1': 'Book your bus ticket now and save big!',
      'dummyAdTitle2': 'Weekend Travel Deals',
      'dummyAdDesc2': 'Explore new destinations every weekend',
      'dummyAdTitle3': 'Premium Lounge Access',
      'dummyAdDesc3': 'Upgrade your travel experience with lounge benefits',
      'dummyAdTitle4': 'Early Bird Special',
      'dummyAdDesc4': 'Book 7 days in advance and get 15% off',
      'dummyAdTitle5': 'Family Package',
      'dummyAdDesc5': 'Travel with family and enjoy group discounts',
      'specialOfferTitle': 'Special Offer! 🎫',
      'specialOfferMessage': 'Get 25% off on your next trip to Kandy.',
      'departsAt': 'Departs {time}',
      'departure': 'Departure',
      'arrival': 'Arrival',
      'book': 'Book',
      'selectStops': 'Select Stops',
      'boardingPoint': 'Boarding Point',
      'alightingPoint': 'Alighting Point',
      'continueToSeatSelection': 'Continue to Seat Selection',
      'searching': 'Searching...',
      'searchTrips': 'Search Trips',
      'enterLocationsToSearch': 'Enter locations to search',
      'tripsFound': '{count} trips found',
      'noOffersRightNow': 'No offers right now',
      'all': 'All',
      'loadingAddress': 'Loading address...',
      'confirmLocation': 'Confirm Location',
      'offersPage': 'Offers Page',
      'toursPage': 'Tours Page',
      'ok': 'OK',
      'retryButton': 'Retry',
      'contactSupportNow': 'Contact Support Now',
      'profileUpdatedSuccessfully': 'Profile updated successfully!',
      'failedToSaveProfile': 'Failed to save profile',
      'saveChanges': 'Save Changes',
      'pleaseEnterYourEmail': 'Please enter your email',
      'pleaseEnterValidEmail': 'Please enter a valid email address',
      'cancelPaymentQuestion': 'Cancel Payment?',
      'continuePayment': 'Continue Payment',
      'tryAgainButton': 'Try Again',
      'receiptWillBeSent': 'Receipt will be sent to your email',
      'myLoungeBookings': 'My Lounge Bookings',
      'upcoming': 'Upcoming',
      'preOrderTotal': 'Pre-order Total:',
      'completePaymentToConfirmBooking': 'Complete payment to confirm booking',
      'bookingSummary': 'Booking Summary',
      'addGuest': 'Add Guest',
      'you': 'You',
      'pleaseEnterGuestName': 'Please enter guest name',
      'selectYourLoungeDuration': 'Select your lounge session duration:',
      'perGuest': 'per guest',
      'selectPricing': 'Select Pricing',
      'dateAndTime': 'Date & Time',
      'guestDetails': 'Guest Details',
      'preOrdersOptional': 'Pre-Orders (Optional)',
      'selectDate': 'Date',
      'checkInTime': 'Check-in Time',
      'primaryGuest': 'Primary Guest',
      'additionalGuests': 'Additional Guests ({count})',
      'preOrderItemsForYourVisit': 'Pre-order items for your lounge visit:',
      'noProductsAvailableForPreOrder': 'No products available for pre-order',
      'bookingConfirmed': 'Booking Confirmed',
      'bookingDetails': 'Booking Details',
      'viewMyBookings': 'View My Bookings',
      'back': 'Back',
      'viewAllLink': 'View All',
      'busBookingConfirmedWithoutLounge':
          'Bus booking confirmed without lounge',
      'appSmsHashTitle': 'Passenger App - SMS Hash',
      'lkrPrefix': 'LKR {amount}',
      'changeLanguage': 'Change Language',
      'selectLanguageAtLoginTitle': 'Select Language',
      'helpAndSupport': 'Help & Support',
      'howCanWeHelp': 'How can we help?',
      'findAnswersOrGetInTouch':
          'Find answers to your questions or get in touch with our team.',
      'frequentlyAskedQuestions': 'Frequently Asked Questions',
      'quickAnswersToCommonIssues': 'Quick answers to common issues',
      'liveChat': 'Live Chat',
      'chatWithOurSupportTeam': 'Chat with our support team',
      'reportAProblem': 'Report a Problem',
      'letUsKnowIfSomethingIsWrong': 'Let us know if something is wrong',
      'stillNeedHelp': 'Still need help?',
      'supportTeamAvailable24X7':
          'Our support team is available 24/7 to assist you with any inquiries.',
      'contactSupportButton': 'Contact Support Now',
      'noMyBookings': 'No bookings yet',
      'startYourFirstJourney': 'Start your first journey today!',
      'cancelPaymentTitle': 'Cancel Payment?',
      'paymentCancellationWarning':
          'Are you sure you want to cancel this payment?',
      'myBookings': 'My Bookings',
      'upcomingTab': 'Upcoming',
      'pastTab': 'Past',
      'cancelledTab': 'Cancelled',
      'noUpcomingBookings': 'No upcoming bookings',
      'noPastTrips': 'No past trips',
      'noCancelledBookings': 'No cancelled bookings',
      'bookNow': 'Book Now',
      'failedToLoadBookings': 'Failed to load bookings',
    },
    sinhala: {
      'profile': 'පැතිකඩ',
      'somethingWentWrong': 'යම් දෝෂයක් සිදු විය',
      'tryAgain': 'නැවත උත්සාහ කරන්න',
      'passenger': 'මගියා',
      'greetingWithName': 'හෙලෝ {name}!',
      'accountManagement': 'ගිණුම් කළමනාකරණය',
      'editProfile': 'පැතිකඩ සංස්කරණය',
      'language': 'භාෂාව',
      'supportLegal': 'සහාය සහ නීති',
      'helpSupport': 'උදව් සහ සහාය',
      'contactUs': 'අප අමතන්න',
      'privacyPolicy': 'රහස්‍යතා ප්‍රතිපත්තිය',
      'getInTouch': 'සම්බන්ධ වන්න',
      'contactUsIntro':
          'ඔබෙන් අසා දැනගැනීමට අපි කැමතියි! කරුණාකර පහත පෝරමය පුරවා හෝ සෘජුවම අප අමතන්න.',
      'phoneLabel': 'දුරකථනය',
      'emailLabel': 'විද්‍යුත් තැපෑල',
      'sendUsAMessage': 'අපට පණිවිඩයක් යවන්න',
      'yourName': 'ඔබගේ නම',
      'yourEmail': 'ඔබගේ විද්‍යුත් තැපෑල',
      'message': 'පණිවිඩය',
      'submitMessage': 'පණිවිඩය යවන්න',
      'messageSentSuccess': 'ඔබගේ පණිවිඩය යවා ඇත!',
      'yourPrivacyMatters': 'ඔබගේ පෞද්ගලිකත්වය වැදගත්ය',
      'privacyPolicyIntro':
          'ඔබ අපගේ Passenger යෙදුම භාවිතා කරන විට ඔබගේ පුද්ගලික තොරතුරු එකතු කරන, භාවිතා කරන සහ බෙදාගන්නා ආකාරය මෙම රහස්‍යතා ප්‍රතිපත්තිය විස්තර කරයි.',
      'privacySection1Title': '1. තොරතුරු එකතු කිරීම',
      'privacySection1Body':
          'ඔබ ගිණුමක් සාදන විට හෝ වෙනස් කරන විට, සේවා ඉල්ලන විට, පාරිභෝගික සහාය අමතන විට හෝ අප සමඟ සන්නිවේදනය කරන විට සෘජුවම ලබාදෙන තොරතුරු අපි එකතු කරමු. මෙයට නම, විද්‍යුත් තැපෑල, දුරකථන අංකය, තැපැල් ලිපිනය, පැතිකඩ පින්තූරය, ගෙවීම් ක්‍රමය සහ ඔබ ලබාදීමට තෝරාගන්නා වෙනත් තොරතුරු ඇතුළත් විය හැක.',
      'privacySection2Title': '2. අපි තොරතුරු භාවිතා කරන ආකාරය',
      'privacySection2Body':
          'ගෙවීම් පහසු කිරීම, රිසිට් යැවීම, ඔබ ඉල්ලන නිෂ්පාදන සහ සේවා ලබාදීම සහ නව විශේෂාංග සංවර්ධනය කිරීම වැනි කටයුතු සඳහා අපගේ සේවාවන් සපයන්න, පවත්වාගෙන යන්න සහ වැඩිදියුණු කරන්න අපි එකතු කරන තොරතුරු භාවිතා කරමු.',
      'privacySection3Title': '3. තොරතුරු බෙදාගැනීම',
      'privacySection3Body':
          'මෙම ප්‍රකාශයේ සඳහන් පරිදි හෝ එකතු කිරීමේ/බෙදාගැනීමේ අවස්ථාවේ දී ඔබ ගැන එකතු කරන තොරතුරු, අප වෙනුවෙන් සේවා සපයන තෙවන පාර්ශවීය සේවා සපයන්නන් සමඟ ද ඇතුළුව, අපි බෙදාගත හැක.',
      'privacySection4Title': '4. දත්ත ආරක්ෂාව',
      'privacySection4Body':
          'අලාභය, සොරකම්, අනිසි භාවිතය සහ අනවසර ප්‍රවේශය, හෙළිදරව් කිරීම, වෙනස් කිරීම හා විනාශයෙන් ඔබේ තොරතුරු ආරක්ෂා කිරීමට අපි සාධාරණ පියවර ගනිමු.',
      'privacyLastUpdated': 'අවසන් යාවත්කාලීනය: 2026 පෙබරවාරි',
      'logoutAccount': 'ගිණුමෙන් පිටවන්න',
      'appVersion': 'ඇප් අනුවාදය',
      'logout': 'පිටවීම',
      'logoutConfirm': 'ඔබට ඇත්තටම පිටවීමට අවශ්‍යද?',
      'staySignedIn': 'පුරනය වී සිටින්න',
      'signOut': 'පිටවන්න',
      'logoutFailed': 'පිටවීම අසාර්ථක විය',
      'selectLanguage': 'භාෂාව තෝරන්න',
      'englishLabel': 'ඉංග්‍රීසි',
      'sinhalaLabel': 'සිංහල',
      'tamilLabel': 'தமிழ்',
      'processing': 'සැකසෙමින්...',
      'loginTitle': 'පිවිසෙන්න',
      'loginSubtitle': 'ඔබගේ ගමන පහසුවෙන් ඉදිරියට ගෙන යාමට පිවිසෙන්න',
      'mobileNumber': 'ජංගම දුරකථන අංකය',
      'pleaseEnterMobileNumber': 'කරුණාකර ඔබගේ ජංගම අංකය ඇතුළත් කරන්න',
      'pleaseEnterValidMobile': 'වලංගු ජංගම අංකයක් ඇතුළත් කරන්න',
      'loginButton': 'පිවිසෙන්න',
      'verificationCodeSent':
          'සත්‍යාපන කේතය යවා ඇත! SMS පණිවිඩය පරීක්ෂා කරන්න.',
      'tooManyRequests': 'අධික ඉල්ලීම්',
      'error': 'දෝෂයක්',
      'failedToSendCode': 'සත්‍යාපන කේතය යැවීමට අසමත් විය',
      'verifying': 'තහවුරු කරමින්...',
      'verifyYourNumber': 'ඔබගේ අංකය තහවුරු කරන්න',
      'enterSixDigitCode': 'මෙම අංකයට යවූ ඉලක්කම් 6 ක කේතය ඇතුළත් කරන්න',
      'verifyContinue': 'තහවුරු කර ඉදිරියට යන්න',
      'didNotReceiveCode': 'කේතය නොලැබුණාද?',
      'resendCode': 'කේතය නැවත යවන්න',
      'resendInSeconds': 'තත්පර {seconds} කින් නැවත යවයි',
      'changeMobileNumber': 'ජංගම අංකය වෙනස් කරන්න',
      'invalidSixDigitCode': 'සම්පූර්ණ ඉලක්කම් 6 ක කේතය ඇතුළත් කරන්න',
      'invalidVerificationCode': 'සත්‍යාපන කේතය වැරදියි. නැවත උත්සාහ කරන්න.',
      'newCodeSent': 'නව කේතය යවා ඇත! SMS පරීක්ෂා කරන්න.',
      'failedToSendCodeRetry': 'කේතය යැවීමට අසමත් විය. නැවත උත්සාහ කරන්න.',
      'completeYourProfile': 'ඔබගේ පැතිකඩ සම්පූර්ණ කරන්න',
      'enterNameToStart': 'ආරම්භ කිරීමට ඔබගේ නම ඇතුළත් කරන්න',
      'firstName': 'මුල් නම',
      'lastName': 'අවසන් නම',
      'enterFirstName': 'මුල් නම ඇතුළත් කරන්න',
      'enterLastName': 'අවසන් නම ඇතුළත් කරන්න',
      'pleaseEnterFirstName': 'කරුණාකර මුල් නම ඇතුළත් කරන්න',
      'pleaseEnterLastName': 'කරුණාකර අවසන් නම ඇතුළත් කරන්න',
      'firstNameMinChars': 'මුල් නම අවම වශයෙන් අක්ෂර 2 ක් විය යුතුය',
      'lastNameMinChars': 'අවසන් නම අවම වශයෙන් අක්ෂර 2 ක් විය යුතුය',
      'continue': 'ඉදිරියට යන්න',
      'addMoreDetailsLater':
          'පසුව ඔබගේ පැතිකඩ සැකසුම් තුළ වැඩි විස්තර එක් කළ හැක',
      'saving': 'සුරකිමින්...',
      'failedToCompleteProfile':
          'පැතිකඩ සම්පූර්ණ කිරීමට අසමත් විය. නැවත උත්සාහ කරන්න.',
      'newNotificationReceived': 'නව දැනුම්දීමක් ලැබී ඇත',
      'view': 'බලන්න',
      'locationsSwapped': 'ස්ථාන මාරු කරන ලදී',
      'searchingTrips': 'ගමන් සෙවෙමින්...',
      'pleaseWait': 'කරුණාකර රැඳී සිටින්න',
      'couldNotFindBusStops': 'තෝරාගත් ස්ථාන සඳහා බස් නැවතුම් හමු නොවුණි',
      'searchFailed': 'සෙවීම අසාර්ථකයි: {error}',
      'locationPermissionDenied': 'ස්ථාන අවසරය ප්‍රතික්ෂේප කළා',
      'locationPermissionPermanentlyDenied':
          'ස්ථාන අවසරය ස්ථිරව ප්‍රතික්ෂේප කර ඇත. සැකසුම් තුළ සක්‍රිය කරන්න.',
      'gettingYourLocation': 'ඔබගේ ස්ථානය ලබා ගනිමින්...',
      'locationSet': 'ස්ථානය සකසා ඇත: {address}',
      'failedToGetCurrentLocation': 'වත්මන් ස්ථානය ලබාගැනීමට අසමත් විය',
      'upcomingTrips': 'ඉදිරි ගමන්',
      'viewAll': 'සියල්ල බලන්න',
      'fromLabel': 'සිට',
      'toLabel': 'දක්වා',
      'enterPickupLocation': 'ආරම්භක ස්ථානය ඇතුළත් කරන්න',
      'enterDestination': 'ගමනාන්තය ඇතුළත් කරන්න',
      'recentSearches': 'මෑත සෙවුම්',
      'searchResults': 'සෙවුම් ප්‍රතිඵල',
      'useCurrentLocation': 'වත්මන් ස්ථානය භාවිතා කරන්න',
      'detectMyLocationGps': 'GPS භාවිතයෙන් මගේ ස්ථානය හඳුනාගන්න',
      'setLocationOnMap': 'සිතියම ස්ථානය සකසන්න',
      'tapToSwapLocations': 'ස්ථාන මාරු කිරීමට තට්ටු කරන්න',
      'busTracking': 'බස් නිරීක්ෂණය',
      'locationPermissionRequired': 'ස්ථාන අවසරය අවශ්‍යයි',
      'enableLocation': 'ස්ථානය සක්‍රිය කරන්න',
      'status': 'තත්ත්වය',
      'trackingActive': 'නිරීක්ෂණය සක්‍රියයි',
      'readyToTrack': 'නිරීක්ෂණයට සූදානම්',
      'route': 'මාර්ගය',
      'stopTracking': 'නිරීක්ෂණය නවත්වන්න',
      'startTracking': 'නිරීක්ෂණය ආරම්භ කරන්න',
      'noActiveBooking': 'සක්‍රීය වෙන් කිරීමක් නැත',
      'bookBusToStartTracking': 'නිරීක්ෂණය ආරම්භ කිරීමට බස් රථයක් වෙන් කරන්න',
      'bookABus': 'බස් රථයක් වෙන් කරන්න',
      'yourLocation': 'ඔබගේ ස්ථානය',
      'na': 'නොමැත',
      'notifications': 'දැනුම්දීම්',
      'showingUnreadOnly': 'නොකියවූ දැනුම්දීම් පමණක්',
      'yourRecentUpdates': 'ඔබගේ මෑත යාවත්කාලීන',
      'allNotificationsMarkedAsRead': 'සියලු දැනුම්දීම් කියවූ ලෙස සලකුණු කළා',
      'deleteNotification': 'දැනුම්දීම මකන්න',
      'removeNotificationPermanently': 'මෙම දැනුම්දීම ස්ථිරව මකා දමන්නද?',
      'cancel': 'අවලංගු',
      'delete': 'මකන්න',
      'notificationDeleted': 'දැනුම්දීම මකා දමන ලදී',
      'markAllRead': 'සියල්ල කියවූ ලෙස සලකුණු කරන්න',
      'refresh': 'නැවුම් කරන්න',
      'testNotification': 'පරීක්ෂණ දැනුම්දීම',
      'welcome': 'සාදරයෙන් පිළිගනිමු!',
      'notificationSystemReady': 'ඔබගේ දැනුම්දීම් පද්ධතිය දැන් සකස් වී ඇත.',
      'noUnreadNotifications': 'නොකියවූ දැනුම්දීම් නොමැත',
      'noNotificationsYet': 'තවම දැනුම්දීම් නොමැත',
      'youAreAllCaughtUp': 'ඔබ සියල්ලටම අලුත්මයි!',
      'updatesWhenArrive': 'යාවත්කාලීන ලැබුණු විට අපි දැනුම් දෙන්නෙමු',
      'oopsSomethingWentWrong': 'අයියෝ! යම් දෝෂයක් සිදු විය',
      'justNow': 'දැන්ම',
      'minutesAgo': 'මිනිත්තු {count} කට පෙර',
      'hoursAgo': 'පැය {count} කට පෙර',
      'daysAgo': 'දින {count} කට පෙර',
      'lounges': 'විවේක මධ්‍යස්ථානය',
      'discoverBookPremiumLounges': 'උසස් විවේක මධ්‍යස්ථානය සොයා වෙන්කරන්න',
      'filterByProvince': 'පළාත අනුව තේරීම',
      'allProvinces': 'සියලු පළාත්',
      'failedToLoadLounges': 'විවේක මධ්‍යස්ථානය පූරණය කිරීමට අසමත් විය',
      'retry': 'නැවත උත්සාහ කරන්න',
      'noLoungesInState': '{state} හි විවේක මධ්‍යස්ථානය නොමැත',
      'noLoungesAvailable': 'විවේක මධ්‍යස්ථානය නොමැත',
      'tryDifferentState': 'වෙනත් පළාතක් තෝරා බලන්න',
      'checkBackLaterLounges':
          'ලබාගත හැකි විවේක මධ්‍යස්ථානය සඳහා පසුව නැවත බලන්න',
      'showAllLounges': 'සියලු විවේක මධ්‍යස්ථානය පෙන්වන්න',
      'loungesInStateCount': '{state} හි විවේක මධ්‍යස්ථානය {count}',
      'showingLoungesCount': 'විවේක මධ්‍යස්ථානය {count}ක් පෙන්වමින්',
      'startingFrom': 'ආරම්භය',
      'available': 'ලබා ගත හැක',
      'closed': 'වසා ඇත',
      'noDateSelected': 'දිනයක් තෝරා නැත',
      'searchFailedTitle': 'සෙවීම අසාර්ථකයි',
      'noBusesForRouteDate': 'තෝරාගත් දිනයේ මෙම මාර්ගයට බස් රථ නොමැත.',
      'noScheduledTrips': 'නියමිත ගමන් නොමැත',
      'routeNotFound': 'මාර්ගය සොයාගත නොහැක',
      'fromPrefix': 'සිට: {value}',
      'toPrefix': 'දක්වා: {value}',
      'changeSearch': 'සෙවීම වෙනස් කරන්න',
      'today': 'අද',
      'tomorrow': 'හෙට',
      'nextMonth': 'ඊළඟ මාසය',
      'inDays': 'දින {days}කින්',
      'popularRoutes': 'ජනප්‍රිය මාර්ග',
      'daySun': 'ඉරි',
      'dayMon': 'සඳු',
      'dayTue': 'අඟ',
      'dayWed': 'බදා',
      'dayThu': 'බ්‍රහස්',
      'dayFri': 'සිකු',
      'daySat': 'සෙන',
      'monthJan': 'ජන',
      'monthFeb': 'පෙබ',
      'monthMar': 'මාර්තු',
      'monthApr': 'අප්‍රේල්',
      'monthMay': 'මැයි',
      'monthJun': 'ජූනි',
      'monthJul': 'ජූලි',
      'monthAug': 'අගෝ',
      'monthSep': 'සැප්',
      'monthOct': 'ඔක්',
      'monthNov': 'නොවැ',
      'monthDec': 'දෙසැ',
      'readyToExplore': 'සංචාරයට සූදානම්ද?',
      'dummyAdTitle1': 'විශේෂ වට්ටම 20% කින් අඩුයි',
      'dummyAdDesc1': 'දැන්ම ඔබගේ බස් ටිකට් වෙන් කර වැඩි ඉතිරියක් ලබා ගන්න!',
      'dummyAdTitle2': 'සති අන්ත ගමන් දීමනා',
      'dummyAdDesc2': 'සෑම සති අන්තයකම නව ගමනාන්ත සොයා බලන්න',
      'dummyAdTitle3': 'උසස් විවේක මධ්‍යස්ථානය ප්‍රවේශය',
      'dummyAdDesc3':
          'විවේක මධ්‍යස්ථානය වාසි සමඟ ඔබගේ ගමන් අත්දැකීම ඉහළ නංවන්න',
      'dummyAdTitle4': 'ඉක්මන් වෙන්කිරීම් විශේෂය',
      'dummyAdDesc4': 'දින 7කට පෙර වෙන් කර 15% වට්ටමක් ලබා ගන්න',
      'dummyAdTitle5': 'පවුල් පැකේජය',
      'dummyAdDesc5': 'පවුල සමඟ ගමන් කර කණ්ඩායම් වට්ටම් ලබා ගන්න',
      'specialOfferTitle': 'විශේෂ දීමනාව! 🎫',
      'specialOfferMessage': 'ඔබගේ මීළඟ කඳුලුම් ගමනට 25% වට්ටමක් ලබා ගන්න.',
      'departsAt': '{time}ට පිටත්වෙයි',
      'departure': 'පිටත්වීම',
      'arrival': 'පැමිණීම',
      'book': 'වෙන් කරන්න',
      'selectStops': 'නැවතුම් තෝරන්න',
      'boardingPoint': 'ගොඩවෙන ස්ථානය',
      'alightingPoint': 'බසින ස්ථානය',
      'continueToSeatSelection': 'ආසන තේරීම වෙත ඉදිරියට යන්න',
      'searching': 'සෙවෙමින්...',
      'searchTrips': 'ගමන් සොයන්න',
      'enterLocationsToSearch': 'සෙවීමට ස්ථාන ඇතුළත් කරන්න',
      'tripsFound': 'ගමන් {count}ක් හමුවිය',
      'noOffersRightNow': 'දැනට දීමනා නොමැත',
      'all': 'සියල්ල',
      'loadingAddress': 'ලිපිනය පූරණය කරමින්...',
      'confirmLocation': 'ස්ථානය තහවුරු කරන්න',
      'offersPage': 'ඔෆර් පිටුව',
      'toursPage': 'සංචාර පිටුව',
      'ok': 'හරි',
      'retryButton': 'නැවත උත්සාහ කරන්න',
      'contactSupportNow': 'දැන්ම සහාය අමතන්න',
      'profileUpdatedSuccessfully': 'පැතිකඩ සফලව යාවත්කාලීන කර ඇත!',
      'failedToSaveProfile': 'පැතිකඩ සුරකිරීමට අසමත් විය',
      'saveChanges': 'වෙනස්කම් සුරකින්න',
      'pleaseEnterYourEmail': 'කරුණාකර ඔබගේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න',
      'pleaseEnterValidEmail':
          'කරුණාකර වලංගු විද්‍යුත් තැපැල් ලිපිනයක් ඇතුළත් කරන්න',
      'cancelPaymentQuestion': 'ගෙවීම අවලංගු කිරීමද?',
      'continuePayment': 'ගෙවීම දිගටම කරන්න',
      'tryAgainButton': 'නැවත උත්සාහ කරන්න',
      'receiptWillBeSent': 'රිසිට් ඔබගේ ඊමේල් ට යවා ඇත',
      'myLoungeBookings': 'මගේ විවේක මධ්‍යස්ථානය වෙන්කිරීම්',
      'upcoming': 'ඉදිරි',
      'preOrderTotal': ' innan දිගටම මුළු ගණන:',
      'completePaymentToConfirmBooking':
          'වෙන්කිරීම තහවුරු කිරීමට ගෙවීම සම්පූර්ණ කරන්න',
      'bookingSummary': 'වෙන්කිරීම් සාරාංශ',
      'addGuest': 'පුපුරුවා එක් කරන්න',
      'you': 'ඔබ',
      'pleaseEnterGuestName': 'කරුණාකර පුපුරුවා පෙර නම ඇතුළත් කරන්න',
      'selectYourLoungeDuration': 'ඔබගේ විවේක මධ්‍යස්ථානය සැසිය තිස්සේ තෝරන්න:',
      'perGuest': 'එක් පුපුරුවා සඳහා',
      'selectPricing': 'මිල තෝරන්න',
      'dateAndTime': 'දිනය සහ කාලය',
      'guestDetails': 'පුපුරුවා විස්තර',
      'preOrdersOptional': 'පෙර ඇණවුම් (විකල්පනීය)',
      'selectDate': 'දිනය',
      'checkInTime': 'පිවිසීමේ කාලය',
      'primaryGuest': 'ප්‍රධාන පුපුරුවා',
      'additionalGuests': 'අතිරේක පුපුරුවා ({count})',
      'preOrderItemsForYourVisit':
          'ඔබගේ විවේක මධ්‍යස්ථානය පිවිසුම සඳහා පෙර ඇණවුම් අයිතම:',
      'noProductsAvailableForPreOrder': 'පෙර ඇණවුම් සඳහා නිෂ්පාදන නොමැත',
      'bookingConfirmed': 'වෙන්කිරීම තහවුරු කර ඇත',
      'bookingDetails': 'වෙන්කිරීම් විස්තර',
      'viewMyBookings': 'මගේ වෙන්කිරීම් බලන්න',
      'back': 'ආපසු යන්න',
      'viewAllLink': 'සියල්ල බලන්න',
      'busBookingConfirmedWithoutLounge':
          'බස් වෙන්කිරීම විවේක මධ්‍යස්ථානය 없이තහවුරු කර ඇත',
      'appSmsHashTitle': 'පැසෙන්ජර් ඇප් - SMS හෙෂ්',
      'lkrPrefix': 'ලක්ෂ {amount}',
      'changeLanguage': 'භාෂාව වෙනස් කරන්න',
      'selectLanguageAtLoginTitle': 'භාෂාව තෝරන්න',
      'helpAndSupport': 'උදව් සහ සහාය',
      'howCanWeHelp': 'අපි ඔබට කෙසේ උදවු දිය හැකිද?',
      'findAnswersOrGetInTouch':
          'ඔබගේ ප්‍රශ්නවලට පිළිතුරු සොයා ගන්න හෝ අපගේ කණ්ඩායම සම්බන්ධ කරන්න.',
      'frequentlyAskedQuestions': 'නිතර අසන ප්‍රශ්න',
      'quickAnswersToCommonIssues': 'සාමාන්‍ය ගැටළුවලට ඉක්මන් පිළිතුරු',
      'liveChat': 'සජීවී කතාබස',
      'chatWithOurSupportTeam': 'අපගේ සහාය කණ්ඩායම සමඟ කතා කරන්න',
      'reportAProblem': 'ගැටළුවක් වාර්තා කරන්න',
      'letUsKnowIfSomethingIsWrong': 'යම් දෝෂයක් ඇත්නම් අපට දන්වන්න',
      'stillNeedHelp': 'තවමත් උදව් අවශ්‍යද?',
      'supportTeamAvailable24X7':
          'අපගේ සහාය කණ්ඩායම ඔබගේ ඕනෑම ප්‍රශ්නයට සඳහා 24/7 සහාය කිරීමට සූදානම්ය.',
      'contactSupportButton': 'දැන්ම සහාය අමතන්න',
      'noMyBookings': 'තවම වෙන්කිරීම් නැත',
      'startYourFirstJourney': 'අද ඔබගේ පළමු ගමන ආරම්භ කරන්න!',
      'cancelPaymentTitle': 'ගෙවීම අවලංගු කිරීමද?',
      'paymentCancellationWarning':
          'ඔබට ඇත්තටම මෙම ගෙවීම අවලංගු කිරීමට අවශ්‍යද?',
      'myBookings': 'මගේ වෙන්කිරීම්',
      'upcomingTab': 'ඉදිරි',
      'pastTab': 'අතීත',
      'cancelledTab': 'අවලංගු කර ඇත',
      'noUpcomingBookings': 'ඉදිරි වෙන්කිරීම් නැත',
      'noPastTrips': 'අතීත ගමන් නැත',
      'noCancelledBookings': 'අවලංගු කරන ලද වෙන්කිරීම් නැත',
      'bookNow': 'දැන් වෙන් කරන්න',
      'failedToLoadBookings': 'වෙන්කිරීම් පූරණය කිරීමට අසමත් විය',
    },
    tamil: {
      'profile': 'சுயவிவரம்',
      'somethingWentWrong': 'ஏதோ பிழை ஏற்பட்டது',
      'tryAgain': 'மீண்டும் முயற்சிக்கவும்',
      'passenger': 'பயணி',
      'greetingWithName': 'வணக்கம் {name}!',
      'accountManagement': 'கணக்கு மேலாண்மை',
      'editProfile': 'சுயவிவரத்தை திருத்து',
      'language': 'மொழி',
      'supportLegal': 'ஆதரவும் சட்டமும்',
      'helpSupport': 'உதவி மற்றும் ஆதரவு',
      'contactUs': 'எங்களை தொடர்பு கொள்ளவும்',
      'privacyPolicy': 'தனியுரிமைக் கொள்கை',
      'getInTouch': 'தொடர்பு கொள்ளுங்கள்',
      'contactUsIntro':
          'உங்களிடமிருந்து கேட்க விரும்புகிறோம்! கீழே உள்ள படிவத்தை நிரப்பவும் அல்லது எங்களை நேரடியாக தொடர்பு கொள்ளவும்.',
      'phoneLabel': 'தொலைபேசி',
      'emailLabel': 'மின்னஞ்சல்',
      'sendUsAMessage': 'எங்களுக்கு ஒரு செய்தி அனுப்புங்கள்',
      'yourName': 'உங்கள் பெயர்',
      'yourEmail': 'உங்கள் மின்னஞ்சல்',
      'message': 'செய்தி',
      'submitMessage': 'செய்தியை அனுப்பு',
      'messageSentSuccess': 'உங்கள் செய்தி அனுப்பப்பட்டது!',
      'yourPrivacyMatters': 'உங்கள் தனியுரிமை முக்கியமானது',
      'privacyPolicyIntro':
          'நீங்கள் எங்கள் Passenger செயலியை பயன்படுத்தும் போது உங்கள் தனிப்பட்ட தகவல்கள் எவ்வாறு சேகரிக்கப்படுகின்றன, பயன்படுத்தப்படுகின்றன மற்றும் பகிரப்படுகின்றன என்பதை இந்த தனியுரிமைக் கொள்கை விளக்குகிறது.',
      'privacySection1Title': '1. தகவல் சேகரிப்பு',
      'privacySection1Body':
          'நீங்கள் கணக்கை உருவாக்கும் போது அல்லது மாற்றும் போது, சேவைகளை கோரும் போது, வாடிக்கையாளர் ஆதரவை தொடர்பு கொள்ளும் போது அல்லது எங்களுடன் தொடர்பு கொள்ளும் போது நீங்கள் நேரடியாக வழங்கும் தகவல்களை நாங்கள் சேகரிக்கிறோம். இதில் பெயர், மின்னஞ்சல், தொலைபேசி எண், அஞ்சல் முகவரி, சுயவிவர படம், கட்டண முறை மற்றும் நீங்கள் வழங்கத் தேர்வு செய்யும் பிற தகவல்கள் அடங்கலாம்.',
      'privacySection2Title': '2. தகவலை எவ்வாறு பயன்படுத்துகிறோம்',
      'privacySection2Body':
          'கட்டணங்களை எளிதாக்க, ரசீதுகளை அனுப்ப, நீங்கள் கோரும் தயாரிப்புகள் மற்றும் சேவைகளை வழங்க மற்றும் புதிய அம்சங்களை உருவாக்க போன்ற வகையில் எங்கள் சேவைகளை வழங்க, பராமரிக்க மற்றும் மேம்படுத்த நாங்கள் சேகரிக்கும் தகவலை பயன்படுத்துகிறோம்.',
      'privacySection3Title': '3. தகவல் பகிர்வு',
      'privacySection3Body':
          'இந்த அறிக்கையில் விவரிக்கப்பட்டபடி அல்லது சேகரிக்கும்/பகிரும் நேரத்தில் கூறப்பட்டபடி, எங்கள் சார்பில் சேவைகளை வழங்கும் மூன்றாம் தரப்பு சேவை வழங்குநர்களுடனும் உங்களைப் பற்றிய தகவலை பகிரலாம்.',
      'privacySection4Title': '4. தரவு பாதுகாப்பு',
      'privacySection4Body':
          'உங்களைப் பற்றிய தகவலை இழப்பு, திருட்டு, தவறான பயன்பாடு மற்றும் அனுமதியற்ற அணுகல், வெளிப்படுத்தல், மாற்றம் மற்றும் அழிவிலிருந்து பாதுகாக்க நாங்கள் நியாயமான நடவடிக்கைகள் எடுக்கிறோம்.',
      'privacyLastUpdated': 'கடைசியாக புதுப்பிக்கப்பட்டது: பிப்ரவரி, 2026',
      'logoutAccount': 'கணக்கில் இருந்து வெளியேறு',
      'appVersion': 'அப் பதிப்பு',
      'logout': 'வெளியேறு',
      'logoutConfirm': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'staySignedIn': 'உள்நுழைந்தே இருங்கள்',
      'signOut': 'வெளியேறு',
      'logoutFailed': 'வெளியேறல் தோல்வியடைந்தது',
      'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'englishLabel': 'English',
      'sinhalaLabel': 'සිංහල',
      'tamilLabel': 'தமிழ்',
      'processing': 'செயலாக்கப்படுகிறது...',
      'loginTitle': 'உள்நுழை',
      'loginSubtitle': 'உங்கள் பயணத்தை தொடர உள்நுழைக',
      'mobileNumber': 'கைபேசி எண்',
      'pleaseEnterMobileNumber': 'உங்கள் கைபேசி எண்ணை உள்ளிடவும்',
      'pleaseEnterValidMobile': 'சரியான கைபேசி எண்ணை உள்ளிடவும்',
      'loginButton': 'உள்நுழை',
      'verificationCodeSent':
          'சரிபார்ப்பு குறியீடு அனுப்பப்பட்டது! SMS ஐ பார்க்கவும்.',
      'tooManyRequests': 'அதிக கோரிக்கைகள்',
      'error': 'பிழை',
      'failedToSendCode': 'சரிபார்ப்பு குறியீட்டை அனுப்ப முடியவில்லை',
      'verifying': 'சரிபார்க்கப்படுகிறது...',
      'verifyYourNumber': 'உங்கள் எண்ணை சரிபார்க்கவும்',
      'enterSixDigitCode':
          'இந்த எண்ணிற்கு அனுப்பப்பட்ட 6 இலக்க குறியீட்டை உள்ளிடவும்',
      'verifyContinue': 'சரிபார்த்து தொடரவும்',
      'didNotReceiveCode': 'குறியீடு கிடைக்கவில்லையா?',
      'resendCode': 'குறியீட்டை மீண்டும் அனுப்பு',
      'resendInSeconds': '{seconds} விநாடிகளில் மீண்டும் அனுப்பலாம்',
      'changeMobileNumber': 'கைபேசி எண்ணை மாற்று',
      'invalidSixDigitCode': 'முழு 6 இலக்க குறியீட்டை உள்ளிடவும்',
      'invalidVerificationCode':
          'தவறான சரிபார்ப்பு குறியீடு. மீண்டும் முயற்சிக்கவும்.',
      'newCodeSent': 'புதிய குறியீடு அனுப்பப்பட்டது! SMS ஐ பார்க்கவும்.',
      'failedToSendCodeRetry':
          'குறியீட்டை அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'completeYourProfile': 'உங்கள் சுயவிவரத்தை பூர்த்தி செய்யவும்',
      'enterNameToStart': 'தொடங்க உங்கள் பெயரை உள்ளிடவும்',
      'firstName': 'முதல் பெயர்',
      'lastName': 'கடைசி பெயர்',
      'enterFirstName': 'உங்கள் முதல் பெயரை உள்ளிடவும்',
      'enterLastName': 'உங்கள் கடைசி பெயரை உள்ளிடவும்',
      'pleaseEnterFirstName': 'முதல் பெயரை உள்ளிடவும்',
      'pleaseEnterLastName': 'கடைசி பெயரை உள்ளிடவும்',
      'firstNameMinChars': 'முதல் பெயர் குறைந்தது 2 எழுத்துகள் இருக்க வேண்டும்',
      'lastNameMinChars': 'கடைசி பெயர் குறைந்தது 2 எழுத்துகள் இருக்க வேண்டும்',
      'continue': 'தொடரவும்',
      'addMoreDetailsLater':
          'பிறகு சுயவிவர அமைப்புகளில் கூடுதல் விவரங்களை சேர்க்கலாம்',
      'saving': 'சேமிக்கப்படுகிறது...',
      'failedToCompleteProfile':
          'சுயவிவரத்தை பூர்த்தி செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'newNotificationReceived': 'புதிய அறிவிப்பு கிடைத்துள்ளது',
      'view': 'பார்க்க',
      'locationsSwapped': 'இடங்கள் மாற்றப்பட்டன',
      'searchingTrips': 'பயணங்கள் தேடப்படுகிறது...',
      'pleaseWait': 'தயவு செய்து காத்திருக்கவும்',
      'couldNotFindBusStops':
          'தேர்ந்தெடுத்த இடங்களுக்கு பேருந்து நிறுத்தங்கள் கிடைக்கவில்லை',
      'searchFailed': 'தேடல் தோல்வியடைந்தது: {error}',
      'locationPermissionDenied': 'இருப்பிட அனுமதி மறுக்கப்பட்டது',
      'locationPermissionPermanentlyDenied':
          'இருப்பிட அனுமதி நிரந்தரமாக மறுக்கப்பட்டது. அமைப்புகளில் இயக்கவும்.',
      'gettingYourLocation': 'உங்கள் இருப்பிடத்தை பெறுகிறது...',
      'locationSet': 'இருப்பிடம் அமைக்கப்பட்டது: {address}',
      'failedToGetCurrentLocation': 'தற்போதைய இருப்பிடத்தை பெற முடியவில்லை',
      'upcomingTrips': 'வரவிருக்கும் பயணங்கள்',
      'viewAll': 'அனைத்தையும் பார்க்க',
      'fromLabel': 'இருந்து',
      'toLabel': 'செல்லும் இடம்',
      'enterPickupLocation': 'புறப்படும் இடத்தை உள்ளிடவும்',
      'enterDestination': 'இலக்கை உள்ளிடவும்',
      'recentSearches': 'சமீபத்திய தேடல்கள்',
      'searchResults': 'தேடல் முடிவுகள்',
      'useCurrentLocation': 'தற்போதைய இருப்பிடத்தை பயன்படுத்து',
      'detectMyLocationGps': 'GPS மூலம் என் இருப்பிடத்தை கண்டறி',
      'setLocationOnMap': 'வரைபடத்தில் இருப்பிடத்தை அமை',
      'tapToSwapLocations': 'இடங்களை மாற்ற தட்டவும்',
      'busTracking': 'பேருந்து கண்காணிப்பு',
      'locationPermissionRequired': 'இருப்பிட அனுமதி தேவை',
      'enableLocation': 'இருப்பிடத்தை இயக்கு',
      'status': 'நிலை',
      'trackingActive': 'கண்காணிப்பு செயல்பாட்டில் உள்ளது',
      'readyToTrack': 'கண்காணிக்க தயாராக உள்ளது',
      'route': 'பாதை',
      'stopTracking': 'கண்காணிப்பை நிறுத்து',
      'startTracking': 'கண்காணிப்பை தொடங்கு',
      'noActiveBooking': 'செயலில் உள்ள முன்பதிவு இல்லை',
      'bookBusToStartTracking': 'கண்காணிக்க பேருந்து முன்பதிவு செய்யவும்',
      'bookABus': 'பேருந்து முன்பதிவு செய்யவும்',
      'yourLocation': 'உங்கள் இருப்பிடம்',
      'na': 'இல்லை',
      'notifications': 'அறிவிப்புகள்',
      'showingUnreadOnly': 'படிக்காத அறிவிப்புகள் மட்டும்',
      'yourRecentUpdates': 'உங்கள் சமீபத்திய புதுப்பிப்புகள்',
      'allNotificationsMarkedAsRead':
          'அனைத்து அறிவிப்புகளும் படித்ததாக குறிக்கப்பட்டது',
      'deleteNotification': 'அறிவிப்பை நீக்கு',
      'removeNotificationPermanently': 'இந்த அறிவிப்பை நிரந்தரமாக நீக்கவா?',
      'cancel': 'ரத்து செய்',
      'delete': 'நீக்கு',
      'notificationDeleted': 'அறிவிப்பு நீக்கப்பட்டது',
      'markAllRead': 'அனைத்தையும் படித்ததாக குறி',
      'refresh': 'புதுப்பி',
      'testNotification': 'சோதனை அறிவிப்பு',
      'welcome': 'வரவேற்கிறோம்!',
      'notificationSystemReady':
          'உங்கள் அறிவிப்பு அமைப்பு இப்போது தயார் நிலையில் உள்ளது.',
      'noUnreadNotifications': 'படிக்காத அறிவிப்புகள் இல்லை',
      'noNotificationsYet': 'இன்னும் அறிவிப்புகள் இல்லை',
      'youAreAllCaughtUp': 'நீங்கள் அனைத்தையும் பார்த்துவிட்டீர்கள்!',
      'updatesWhenArrive': 'புதிய புதுப்பிப்புகள் வந்தவுடன் தெரிவிப்போம்',
      'oopsSomethingWentWrong': 'அப்பா! ஏதோ பிழை ஏற்பட்டது',
      'justNow': 'இப்போதுதான்',
      'minutesAgo': '{count}நி முன்',
      'hoursAgo': '{count}மணி முன்',
      'daysAgo': '{count}நாள் முன்',
      'lounges': 'லவுஞ்சுகள்',
      'discoverBookPremiumLounges':
          'பிரீமியம் லவுஞ்சுகளை கண்டறிந்து முன்பதிவு செய்யவும்',
      'filterByProvince': 'மாநிலத்தின் அடிப்படையில் வடிகட்டி',
      'allProvinces': 'அனைத்து மாநிலங்கள்',
      'failedToLoadLounges': 'லவுஞ்சுகளை ஏற்ற முடியவில்லை',
      'retry': 'மீண்டும் முயற்சி',
      'noLoungesInState': '{state} பகுதியில் லவுஞ்சுகள் இல்லை',
      'noLoungesAvailable': 'லவுஞ்சுகள் இல்லை',
      'tryDifferentState': 'வேறு மாநிலத்தை தேர்வு செய்து பார்க்கவும்',
      'checkBackLaterLounges':
          'கிடைக்கும் லவுஞ்சுகளுக்கு பிறகு மீண்டும் பார்க்கவும்',
      'showAllLounges': 'அனைத்து லவுஞ்சுகளையும் காட்டு',
      'loungesInStateCount': '{state} பகுதியில் {count} லவுஞ்ச்',
      'showingLoungesCount': '{count} லவுஞ்சுகள் காட்டப்படுகிறது',
      'startingFrom': 'ஆரம்ப விலை',
      'available': 'கிடைக்கும்',
      'closed': 'மூடப்பட்டது',
      'noDateSelected': 'தேதி தேர்ந்தெடுக்கப்படவில்லை',
      'searchFailedTitle': 'தேடல் தோல்வியடைந்தது',
      'noBusesForRouteDate':
          'தேர்ந்தெடுத்த தேதியில் இந்த பாதைக்கு பேருந்துகள் இல்லை.',
      'noScheduledTrips': 'திட்டமிட்ட பயணங்கள் இல்லை',
      'routeNotFound': 'பாதை கிடைக்கவில்லை',
      'fromPrefix': 'இருந்து: {value}',
      'toPrefix': 'செல்லும் இடம்: {value}',
      'changeSearch': 'தேடலை மாற்று',
      'today': 'இன்று',
      'tomorrow': 'நாளை',
      'nextMonth': 'அடுத்த மாதம்',
      'inDays': '{days} நாட்களில்',
      'popularRoutes': 'பிரபலமான பாதைகள்',
      'daySun': 'ஞாயி',
      'dayMon': 'திங்கள்',
      'dayTue': 'செவ்',
      'dayWed': 'புதன்',
      'dayThu': 'வியா',
      'dayFri': 'வெள்',
      'daySat': 'சனி',
      'monthJan': 'ஜன',
      'monthFeb': 'பிப்',
      'monthMar': 'மார்',
      'monthApr': 'ஏப்',
      'monthMay': 'மே',
      'monthJun': 'ஜூன்',
      'monthJul': 'ஜூலை',
      'monthAug': 'ஆக',
      'monthSep': 'செப்',
      'monthOct': 'அக்',
      'monthNov': 'நவ',
      'monthDec': 'டிச',
      'readyToExplore': 'சுற்றுலா செல்ல தயார் தானா?',
      'dummyAdTitle1': 'சிறப்பு தள்ளுபடி 20% OFF',
      'dummyAdDesc1':
          'இப்போதே உங்கள் பேருந்து டிக்கெட்டை முன்பதிவு செய்து அதிகம் சேமிக்கவும்!',
      'dummyAdTitle2': 'வார இறுதி பயண சலுகைகள்',
      'dummyAdDesc2': 'ஒவ்வொரு வார இறுதியிலும் புதிய இடங்களை கண்டறியுங்கள்',
      'dummyAdTitle3': 'பிரீமியம் லவுஞ்ச் அணுகல்',
      'dummyAdDesc3':
          'லவுஞ்ச் நன்மைகளுடன் உங்கள் பயண அனுபவத்தை மேம்படுத்துங்கள்',
      'dummyAdTitle4': 'முன்பதிவு சிறப்பு சலுகை',
      'dummyAdDesc4':
          '7 நாட்களுக்கு முன் முன்பதிவு செய்து 15% தள்ளுபடி பெறுங்கள்',
      'dummyAdTitle5': 'குடும்பப் பேக்கேஜ்',
      'dummyAdDesc5':
          'குடும்பத்துடன் பயணம் செய்து குழு தள்ளுபடிகளை அனுபவிக்கவும்',
      'specialOfferTitle': 'சிறப்பு சலுகை! 🎫',
      'specialOfferMessage':
          'கண்டி செல்லும் உங்கள் அடுத்த பயணத்திற்கு 25% தள்ளுபடி பெறுங்கள்.',
      'departsAt': '{time} புறப்படுகிறது',
      'departure': 'புறப்படும் இடம்',
      'arrival': 'சென்று சேரும் இடம்',
      'book': 'முன்பதிவு செய்',
      'selectStops': 'நிறுத்தங்களை தேர்வு செய்',
      'boardingPoint': 'ஏறும் இடம்',
      'alightingPoint': 'இறங்கும் இடம்',
      'continueToSeatSelection': 'இருக்கை தேர்வுக்கு தொடரவும்',
      'searching': 'தேடுகிறது...',
      'searchTrips': 'பயணங்களை தேடு',
      'enterLocationsToSearch': 'தேட இடங்களை உள்ளிடவும்',
      'tripsFound': '{count} பயணங்கள் கிடைத்தன',
      'noOffersRightNow': 'தற்போது சலுகைகள் இல்லை',
      'all': 'அனைத்தும்',
      'loadingAddress': 'முகவரி ஏற்றப்படுகிறது...',
      'confirmLocation': 'இருப்பிடத்தை உறுதிப்படுத்து',
      'offersPage': 'சலுகைகள் பக்கம்',
      'toursPage': 'சுற்றுலா பக்கம்',
      'ok': 'சரி',
      'retryButton': 'மீண்டும் முயற்சி',
      'contactSupportNow': 'இப்போது ஆதரவை தொடர்பு கொள்ளவும்',
      'profileUpdatedSuccessfully':
          'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      'failedToSaveProfile': 'சுயவிவரத்தை சேமிக்க முடியவில்லை',
      'saveChanges': 'மாற்றங்களை சேமிக்கவும்',
      'pleaseEnterYourEmail': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      'pleaseEnterValidEmail': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'cancelPaymentQuestion': 'கட்டணத்தை ரத்து செய்யவா?',
      'continuePayment': 'கட்டணத்தை தொடரவும்',
      'tryAgainButton': 'மீண்டும் முயற்சி',
      'receiptWillBeSent': 'ரசீது உங்கள் மின்னஞ்சலுக்கு அனுப்பப்படும்',
      'myLoungeBookings': 'என் லவுஞ்சு முன்பதிவுகள்',
      'upcoming': 'வரவிருக்கும்',
      'preOrderTotal': 'முன்பதிவு மொத்தம்:',
      'completePaymentToConfirmBooking':
          'முன்பதிவை உறுதிப்படுத்த கட்டணத்தை பூர்த்தி செய்யவும்',
      'bookingSummary': 'முன்பதிவு சாரண்யம்',
      'addGuest': 'விருந்தினரைச் சேர்க்க',
      'you': 'நீங்கள்',
      'pleaseEnterGuestName': 'விருந்தினரின் பெயரை உள்ளிடவும்',
      'selectYourLoungeDuration':
          'உங்கள் லவுஞ்சு செশন கால அளவைத் தேர்ந்தெடுக்கவும்:',
      'perGuest': 'ஒரு விருந்தினருக்கு',
      'selectPricing': 'விலைத் திட்டத்தைத் தேர்ந்தெடுக்கவும்',
      'dateAndTime': 'தேதி மற்றும் நேரம்',
      'guestDetails': 'விருந்தினர் விவரங்கள்',
      'preOrdersOptional': 'முன்பதிவு (விருப்பத்துக்கியது)',
      'selectDate': 'தேதி',
      'checkInTime': 'செக் இன் நேரம்',
      'primaryGuest': 'முதன்மை விருந்தினர்',
      'additionalGuests': 'கூடுதல் விருந்தினர்கள் ({count})',
      'preOrderItemsForYourVisit':
          'உங்கள் லவுஞ்சு பயணத்திற்கான முன்பதிவு பொருட்கள்:',
      'noProductsAvailableForPreOrder': 'முன்பதிவுக்கு பொருட்கள் கிடைக்கவில்லை',
      'bookingConfirmed': 'முன்பதிவு உறுதிப்படுத்தப்பட்டது',
      'bookingDetails': 'முன்பதிவு விவரங்கள்',
      'viewMyBookings': 'என் முன்பதிவுகளைப் பார்க்கவும்',
      'back': 'பின்னுக்குச் செல்லவும்',
      'viewAllLink': 'அனைத்தையும் பார்க்கவும்',
      'busBookingConfirmedWithoutLounge':
          'பேருந்து முன்பதிவு லவுஞ்சு இல்லாமல் உறுதிப்படுத்தப்பட்டது',
      'appSmsHashTitle': 'பயணி ஆப் - SMS ஹேஷ்',
      'lkrPrefix': 'LKR {amount}',
      'changeLanguage': 'மொழியை மாற்றுக',
      'selectLanguageAtLoginTitle': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'helpAndSupport': 'உதவி மற்றும் ஆதரவு',
      'howCanWeHelp': 'நாம் உங்களுக்கு எப்படি உதவ முடியும்?',
      'findAnswersOrGetInTouch':
          'உங்கள் கேள்விகளுக்கான பதிலைக் கண்டுபிடிக்க அல்லது எங்கள் குழுவைத் தொடர்பு கொள்ளவும்.',
      'frequentlyAskedQuestions': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'quickAnswersToCommonIssues': 'பொதுவான சிக்கல்களுக்கான விரைவான பதிலები',
      'liveChat': 'நேரடி அரட்டை',
      'chatWithOurSupportTeam': 'எங்கள் ஆதரவு குழுவுடன் அரட்டை செய்யவும்',
      'reportAProblem': 'சிக்கலைப் புகாரளிக்க',
      'letUsKnowIfSomethingIsWrong':
          'ஏதாவது தவறு இருந்தால் எங்களுக்குத் தெரியப்படுத்தவும்',
      'stillNeedHelp': 'இன்னும் உதவி தேவையா?',
      'supportTeamAvailable24X7':
          'எங்கள் ஆதரவு குழு உங்கள் எந்த கேள்விக்கும் 24/7 உதவிக்கு கிடைக்கிறது.',
      'contactSupportButton': 'இப்போது ஆதரவை தொடர்பு கொள்ளவும்',
      'noMyBookings': 'இன்னும் முன்பதிவுகள் இல்லை',
      'startYourFirstJourney': 'இன்று உங்கள் முதல் பயணத்தைத் தொடங்கவும்!',
      'cancelPaymentTitle': 'கட்டணத்தை ரத்து செய்யவா?',
      'paymentCancellationWarning':
          'நிச்சயமாக இந்த கட்டணத்தை ரத்து செய்ய விரும்புகிறீர்களா?',
      'myBookings': 'என் முன்பதிவுகள்',
      'upcomingTab': 'வரவிருக்கும்',
      'pastTab': 'கடந்த',
      'cancelledTab': 'ரத்து செய்யப்பட்ட',
      'noUpcomingBookings': 'வரவிருக்கும் முன்பதிவுகள் இல்லை',
      'noPastTrips': 'கடந்த பயணங்கள் இல்லை',
      'noCancelledBookings': 'ரத்து செய்யப்பட்ட முன்பதிவுகள் இல்லை',
      'bookNow': 'இப்போது முன்பதிவு செய்யவும்',
      'failedToLoadBookings': 'முன்பதிவுகளை ஏற்ற முடியவில்லை',
    },
  };

  static String tr(BuildContext context, String key) {
    final languageCode = context.read<LanguageProvider>().languageCode;
    return _values[languageCode]?[key] ?? _values[english]?[key] ?? key;
  }

  static String languageName(BuildContext context, String languageCode) {
    switch (languageCode) {
      case english:
        return tr(context, 'englishLabel');
      case sinhala:
        return tr(context, 'sinhalaLabel');
      case tamil:
        return tr(context, 'tamilLabel');
      default:
        return tr(context, 'englishLabel');
    }
  }

  static String trWithArgs(
    BuildContext context,
    String key,
    Map<String, String> args,
  ) {
    var value = tr(context, key);
    args.forEach((argKey, argValue) {
      value = value.replaceAll('{$argKey}', argValue);
    });
    return value;
  }
}
